### ISSUE TITLE
Add feature-full slot

### ISSUE THREAD

**Issue by blakemorgan** [byuweb/byu-feature-card#17]
Add `full-feature` slot

**Comment by rburkey87** [comment]
@bmorgan296 - I might be able to help with this, but I need more clarification

**Comment by blakemorgan** [comment]
Instead of having two slots on top and one on bottom, make it an option for one on bottom and one on top

**Comment by katrialesser** [comment]
we might want to call this top- something to clarify that it would be top above the other areas. More specific is probably best.

**Comment by katrialesser** [comment]
Fixed with new release!
