### ISSUE TITLE
Text is wrapping strangely and overflowing the boundaries

### ISSUE THREAD

**Issue by kevin-larry-bauer** [byuweb/byu-feature-card#21]
When multiple items are in the feature-right slot they wrap strangely and can overflow the boundaries. A good example is on http://webcommunity.byu.edu/byu-features. This could just be an issue with how the component is being used, but this could potentially be fixed by having the feature-right slot use css flexbox.

**Comment by rburkey87** [comment]
@kebowdog - the only time I see this happening is that at certain widths, the web community email is too long for the slot. I'm not sure if flexbox could fix that unless the whole region shifted under the logo...

**Comment by kevin-larry-bauer** [comment]
Good Point, it looks like it's just that width, and just for links. I'll close it for now since that's not really an issue with the component so much as it's an issue with the markup itself.
